New Mod: Rune Opener List
prixe/lindo pull request #150
Opened 2021-11-13 18:21 UTC by MinZe25

Each time a fragment rune is opened it will send a message with the new items opened.

![image](https://user-images.githubusercontent.com/22060140/141654548-fd72dc67-d1a2-4640-939c-ae3c3e7b1b49.png)

2021-11-15 09:19 UTC, JulienCoutault requested changes
Unsing TranslatitionService will be better.

And why do you have 24k deletion into package-lock ?

I like the idea, thanks for the pr

2021-11-15 09:19 UTC, JulienCoutault commented on src/app/mods/rune-lister/runeOpenerLister.ts
> +    };
You should put translations into /locales/ files instead of here

2021-11-15 09:19 UTC, JulienCoutault commented on src/app/windows/main/layout/game/game.component.ts
> +
Once you will use TranslationService, this case will be useless

2021-11-15 17:09 UTC, MinZe25 commented
I've improved the spanish translation (and added a change in the english one)

2021-12-02 18:03 UTC, JulienCoutault approved these changes

2021-12-09 17:09 UTC, merged