Typescript Type hinting
prixe/lindo pull request #155
Opened 2021-12-12 14:02 UTC by Sylvaner

Proposition d'interface pour les objets du client Dofus. Cela permet de vérifier la syntaxe pendant le développement et donne des informations sur la structure des objets connus.
C'est bien entendu incomplet et permet de compiler, il serait intéressant pour certains de compléter les informations.
Le 2e commit fait la même chose pour les messages.

2021-12-17 18:22 UTC, JulienCoutault requested changes
Not up to date with the last pr merged

2021-12-17 20:05 UTC, Sylvaner commented
Updated

2021-12-19 12:27 UTC, Sylvaner commented
I don't understand, i merged last develop and added missing things.
I missing something ?

2021-12-22 16:48 UTC, JulienCoutault approved these changes

2021-12-22 17:52 UTC, JulienCoutault approved these changes

2022-01-10 10:20 UTC, merged