Autofocus du input HDV
prixe/lindo pull request #157
Opened 2021-12-18 11:59 UTC by TheKetur55

Je ves rajouter tout les inputs du jeu pour avoir un focus directement

2021-12-18 12:01 UTC, TheKetur55 commented
Ajout d'un auto focus : 

- Amis
- Bestiaire
- Succes

Ajout d'une barre de recherche : 

- Quetes

2021-12-23 10:52 UTC, JulienCoutault requested changes
Il faut aussi que tu passes le nom de tes fonctions en camelCase

2021-12-23 10:52 UTC, JulienCoutault commented on src/app/mods/general/auto-focus.ts
> +            if (e.tabId === 'achievements') {
Pourquoi etre passe par un autre find ? Tu peux juste faire un else dans celui de dessus

2021-12-23 10:52 UTC, JulienCoutault commented on src/app/mods/general/auto-focus.ts
> +        this.wGame.gui.windowsContainer._childrenList.find(e=>e.id=="grimoire").on("open",(e)=>{
Comme dis sur discord, je pense qu'il vaut mieux utiliser la fonction `getChildren` que de prendre directement l'attribut

2022-01-10 15:47 UTC, TheKetur55 commented on src/app/mods/general/auto-focus.ts
> +            if (e.tabId === 'achievements') {
pas bete

2022-01-10 17:02 UTC, TheKetur55 commented
Pret a etre merge pour moi

2022-01-10 18:42 UTC, MirageMaPomme commented
Tu devrais peut-être factoriser tes fonctions de focus pour n’en avoir qu’1 seule générique, car c’est uniquement le querySelector qui change

2022-01-16 17:22 UTC, MirageMaPomme commented
Je suis certain que tu pourrais aussi factoriser le startMod 😁
Mais c’est déjà beaucoup mieux !

2022-01-17 16:42 UTC, TheKetur55 commented
Pret a etre merge sur la prochaine beta

2022-02-04 17:58 UTC, merged