Show ressources
prixe/lindo pull request #91
Opened 2020-12-19 23:51 UTC by maximeBailly

Add mod for display all resources on map with a shortcut.

2020-12-20 11:41 UTC, Maryannah requested changes

2020-12-20 11:41 UTC, Maryannah commented on locale/en.json
> +            "show-resources-shortcut" : "Shortcut for show/hide map resources"
`to show/hide`

2020-12-20 11:41 UTC, Maryannah commented on src/app/core/mods/showResources/resources.ts
> +        if (this.resources.length > 0 && this.resources.find(r => r.elemId == resource.elementId) != undefined) {
`if (this.resources.length && this.resources.find(r => r.elemId == resource.elementId)) {`

2020-12-20 11:41 UTC, Maryannah commented on src/app/core/mods/showResources/resources.ts
> +        if (this.resources.length > 0 && this.resources.find(r => r.elemId == resource.elementId) != undefined) {
Event better 

```
const ref = this.resources.find(r => r.elemId == resource.elementId);
if (ref) ref.state = resource.elementState;
else this.resources.push({elemId: resource.elementId, state: resource.elementState})
```

2020-12-20 11:41 UTC, Maryannah commented on src/app/core/mods/showResources/resources.ts
> +    public getName(): string {
name seems to be a constant, so need to use a getter : instead, make the property public and readonly

2020-12-20 11:41 UTC, Maryannah commented on src/app/core/mods/showResources/showResources.ts
> +            this.wGame.document.getElementsByTagName('head')[0].appendChild(resourcesBoxCss);
`this.wGame.document.querySelector('head').appendChild(resourcesBoxCss);`

2021-01-25 10:42 UTC, JulienCoutault approved these changes

2021-01-31 16:05 UTC, merged